spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parental_control
    username: root
    password: toor
    driverClassName: com.mysql.jdbc.Driver
  profiles: #CONFIG DEFAULT PROFILE
    active: homolog
server:
  port: 8082